# 1) Construir arrays a partir de una lista simple y una lista anidada usando tipos de datos numéricos distintos para cada una.

In [6]:
import numpy as np

# Array a partir de una lista simple (números enteros)

lista_simple = [1, 2, 3, 4, 5]
array_simple = np.array(lista_simple, dtype=int)
print("Array desde lista simple:", array_simple)

# Array a partir de una lista anidada (números decimales)

lista_anidada = [[1.1, 2.2], [3.3, 4.4]]
array_anidado = np.array(lista_anidada, dtype=float)
print("Array desde lista anidada:\n", array_anidado)

Array desde lista simple: [1 2 3 4 5]
Array desde lista anidada:
 [[1.1 2.2]
 [3.3 4.4]]


# 2) Construir un array lineal de 36 elementos. Cambiar el shape para que tenga: a) 3 filas y 12 columnas. b) 4 columnas

In [8]:

# Creo un array lineal de 36 elementos (del 1 al 36)
array_lineal = np.arange(1, 37)
print("Array lineal de 36 elementos:\n", array_lineal)

# (Inciso a) Cambio el shape a 3 filas y 12 columnas

array_3x12 = array_lineal.reshape(3, 12)
print("\nArray con shape 3x12:\n", array_3x12)

# (Inciso b) Cambio el shape a 9 filas y 4 columnas ya que 4x9=36

array_9x4 = array_lineal.reshape(9, 4)
print("\nArray con shape 9x4:\n", array_9x4)

Array lineal de 36 elementos:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]

Array con shape 3x12:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]

Array con shape 9x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]]


# 3) Dado un vector de pesos(kg) y otro vector alturas(metros), calcular el índice de masa corporal general (un vector imc).


In [9]:
pesos = np.array([50,65.5,89.2,100])
alturas = np.array([1.6,1.7,1.8,1.75])

In [10]:
# Vectores de pesos y alturas

pesos = np.array([50, 65.5, 89.2, 100])
alturas = np.array([1.6, 1.7, 1.8, 1.75])

# Cálculo del IMC para cada par de peso y altura (peso sobre altura al cuadrado)

imc = pesos / (alturas ** 2)
print("Vector de IMC:", imc)

Vector de IMC: [19.53125    22.66435986 27.5308642  32.65306122]


# 4) Crear un vector con diez números, todos ceros. 


In [3]:
import numpy as np

vector_ceros = np.zeros(10)
print("Vector de diez ceros:", vector_ceros)

Vector de diez ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 5) Crear un vector con diez números al azar.


In [5]:
# Si utilizo "rand" me arroja decimales entre 0 y 1

vector_aleatorio = np.random.rand(10)
print("Vector de diez números al azar:", vector_aleatorio)

Vector de diez números al azar: [0.1774404  0.28414265 0.26127023 0.73930515 0.15732684 0.57565156
 0.80049354 0.90060027 0.35671829 0.40639126]


In [6]:
# Si utilizo "randit" me arroja decimales entre el rango que especifique, en este caso entre 1 y 100

vector_aleatorio_enteros = np.random.randint(1, 101, size=10)
print("Vector de diez números enteros al azar:", vector_aleatorio_enteros)

Vector de diez números enteros al azar: [93 31 75 58 60 82  4 54  4 12]


# 6) Crear una matriz de 2x3 y multiplicarla por su traspuesta. Lo pedido sería algo así: A*AT . 


In [8]:
# Creo la matriz de 2x3

A = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz A:\n", A)

# Luego calculo la transpuesta de A

A_T = A.T
print("\nTranspuesta de A (A^T):\n", A_T)

# Y por último multiplico A por su transpuesta A_T

producto = np.dot(A, A_T)
print("\nProducto de A y A^T (A * A^T):\n", producto)

Matriz A:
 [[1 2 3]
 [4 5 6]]

Transpuesta de A (A^T):
 [[1 4]
 [2 5]
 [3 6]]

Producto de A y A^T (A * A^T):
 [[14 32]
 [32 77]]
